### ISSUE TITLE
Freezes when a large number of nodes

### ISSUE THREAD

**Issue by Navka1** [Siccity/SerializableCallback#12]
First at all thank you for your amazing job.

I use your framework for dialogue system and at now there is about 430 nodes in one asset. I started to notice that the more nodes, the more the editor freezes. Especially noticable when inputing in TextArea or string input. 

Also I noticed that reopening editor removes freezes for a while.

I'm really new in Unity, but about month creating my own dialogue system and all that I can provide to help me it`s screenshot from profiler. 

Maybe you can know some tricks or important nuances when use your framework to avoid freezes?

THX!

![image](https://user-images.githubusercontent.com/26325879/79787718-1f103680-8350-11ea-8cdf-7e42f8741e84.png)

**Comment by Siccity** [comment]
430 nodes is a lot of nodes. You should look into splitting it into several graphs

**Comment by Navka1** [comment]
Thank you, I thought about this  idea but it's not very convenient. Before using this solution I was looking for ways of speeding large graphs. But if you don't have any ideas about it, splitting is the most useful decision.

**Comment by Siccity** [comment]
There is the possibility of implementing LOD node editors, which will significantly increase framerate when zoomed out. Its not built-in so you will have to implement it yourself using custom node editors. I know there are some people on the discord channel who have done this before.
