### ISSUE TITLE
package.json does not include a meta file, preventing the package from compiling

### ISSUE THREAD

**Issue by Leoul** [Siccity/SerializableCallback#16]
Errors when importing the package via manifest.json:
- Asset Packages/com.github.siccity.serializablecallback/package.json has no meta file, but it's in an immutable folder. The asset will be ignored.
- Asset Packages/com.github.siccity.serializablecallback/LICENSE.md has no meta file, but it's in an immutable folder. The asset will be ignored.
- Asset Packages/com.github.siccity.serializablecallback/README.md has no meta file, but it's in an immutable folder. The asset will be ignored.

Unity fails to create an assembly definition file as a result of package.json being ignored, and then continues to ignore all .cs files in the package. A fairly simple fix should be able to be achieved just by adding appropriate meta files to the repo.

Repro is on Unity 2020.1.0b12.3931 Personal

**Comment by Siccity** [comment]
Fixed in 4c5aa21
