### ISSUE TITLE
Import errors 'TargetConstraintAttribute' could not be found

### ISSUE THREAD

**Issue by Tymski** [Siccity/SerializableCallback#23]
Hi I added the link from readme to my manifest. I get 3 errors CS0246 in the Unity console.

`Library\PackageCache\com.github.siccity.serializablecallback@63a8c1e919752300252f27ea69762bb35088802d\Editor\SerializableCallbackDrawer.cs(10,30): error CS0246: The type or namespace name 'TargetConstraintAttribute' could not be found (are you missing a using directive or an assembly reference?)`

I'm using Unity 2018.4.26f1 LTS

**Comment by Siccity** [comment]
Make sure the editor assembly references the runtime one. See if that fixes it

**Comment by felipeggrod** [comment]
The assembly definitions in the editor folder is referencing the one in runtime folder, but it still gives a bunch of compiling errors
